name: test
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
      ELASTICSEARCH_SINK_NUM_WORKERS: 1
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod download

      - name: Run test
        run: go test ./...
